# Generated by Django 5.2.11 on 2026-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_fertilizer_alter_watering_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizer',
            field=models.ManyToManyField(to='my_app.fertilizer'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='fert_type',
            field=models.CharField(choices=[('L', 'Liquid'), ('O', 'Organic'), ('S', 'Slow-Release')], default='L', max_length=1),
        ),
    ]
