# Generated by Django 5.2.11 on 2026-02-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_plant_fertilizer_alter_fertilizer_fert_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='fertilizer',
            new_name='fertilizers',
        ),
    ]
